import {BadgeCheck,Eye,HeartHandshake,MousePointerClick,Search,Target,type LucideIcon} from "lucide-react";
export const problems=[
 ["I’m getting traffic, but almost no sales.","People browse products, then leave without adding to cart.","Traffic intent, offer clarity, product presentation, trust or mobile friction may be misaligned.","Traffic sources, landing paths, behavior signals, product pages and the offer customers actually see.","A prioritized conversion plan that fixes the biggest points of hesitation first."],
 ["My ads are becoming too expensive.","Clicks cost more, reporting feels unreliable and profitable orders are harder to find.","Campaign-to-page mismatch, weak tracking, broad targeting or an offer that cannot carry acquisition costs.","Tracking quality, audience intent, creative alignment, landing experience and contribution margin.","Cleaner measurement and a tighter path from advertisement to purchase."],
 ["Customers add products and disappear.","Strong interest reaches the cart, but too few customers finish payment.","Late shipping surprises, payment gaps, checkout friction or unanswered delivery questions.","Cart behavior, mobile checkout, shipping disclosure, payment methods and abandonment messages.","A clearer, lower-friction purchase flow and useful recovery journeys."],
 ["My store doesn’t feel trustworthy enough.","The site is live, but shoppers still hesitate to enter payment details.","Thin proof, unclear policies, inconsistent design or vague delivery details.","Trust architecture, reviews, policies, navigation and credibility signals.","A more reassuring storefront that answers risk-related questions before checkout."],
 ["Customers buy once and never return.","Revenue depends on continually finding another first-time customer.","Weak post-purchase communication, generic discount emails or no useful reason to return.","Lifecycle data, customer segments, replenishment timing, email flows and repeat-purchase paths.","Retention journeys that stay helpful, relevant and commercially sensible."],
 ["I don’t know what is actually broken.","There is plenty of data and advice, but no dependable order of action.","Disconnected tools, simultaneous changes, technical debt and recommendations without context.","The complete customer journey, technical health, analytics and the relationship between symptoms.","A diagnosis that separates urgent revenue leaks from low-impact distractions."]
] as const;
export type Stage={name:string;problem:string;help:string;Icon:LucideIcon}; export const stages:Stage[]=[
 {name:"Attract",problem:"Wrong or expensive traffic",help:"Traffic quality, campaign alignment and acquisition analysis",Icon:Target},{name:"Convince",problem:"Visitors do not understand why they should purchase",help:"Offers, product positioning, merchandising and product-page improvement",Icon:MousePointerClick},{name:"Reassure",problem:"The store does not create enough confidence",help:"Reviews, policies, delivery messaging, proof and trust architecture",Icon:BadgeCheck},{name:"Convert",problem:"Customers encounter friction before payment",help:"Cart, checkout, mobile UX and payment-flow optimization",Icon:HeartHandshake},{name:"Retain",problem:"Customers purchase once and disappear",help:"Email automation, post-purchase journeys, loyalty and win-back systems",Icon:Eye},{name:"Discover",problem:"The business depends entirely on advertising",help:"Ecommerce SEO, content architecture and AI-search visibility",Icon:Search}];
export const solutions=[["Ecommerce Conversion Improvement","Traffic arrives but sales do not follow."],["Store Design and User Experience","The storefront feels confusing, dated or difficult on mobile."],["Product Page Optimization","Product pages inform shoppers without persuading them."],["Cart and Checkout Recovery","Interested customers leave before payment."],["Ecommerce SEO and AI Visibility","The store is hard to discover without paid advertising."],["Customer Retention and Email Systems","Customers purchase once and disappear."],["Performance and Technical Optimization","Slow pages and technical debt make every visit harder."],["Analytics and Revenue-Leak Diagnosis","Data exists, but it does not provide direction."]] as const;
